name: sentra_mobile
description: "Sentra Parking - Smart Parking Management"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_stripe: ^11.5.0
  get_it: ^9.2.0
  google_fonts: ^6.3.3
  supabase_flutter: ^2.12.0
  dartz: ^0.10.1
  go_router: ^14.6.3
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  shared_preferences: ^2.3.5
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
